server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;  # Apunta al directorio 'public' de Laravel
    index index.php index.html index.htm;

    # Servir los archivos estáticos
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pasar las solicitudes PHP a PHP-FPM
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;  # PHP-FPM escucha en el puerto 9000
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        include fastcgi_params;
    }

    # Bloquear el acceso a archivos ocultos
    location ~ /\.ht {
        deny all;
    }
}
