server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;  # Apunta al directorio 'public' de Laravel
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;  # Si no existe el archivo, pasa la solicitud a PHP
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;  # PHP-FPM escucha en el puerto 9000
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        include fastcgi_params;  # Cargar parámetros necesarios para el paso a PHP-FPM
    }

    location ~ /\.ht {
        deny all;  # Prohibir acceso a archivos ocultos
    }
}
